export const Houses = [
  {
    id: 1,
    name: 'Guest House',
    image: require('../assets/images/house3.jpg'),
    housePackage: 'Rs. 200,000/Year',
    bedroom: 5,
    bathroom: 2,
    address: 'Anna Nagar',
  },
  {
    id: 2,
    name: 'Lux House',
    image: require('../assets/images/house2.jpg'),
    housePackage: 'Rs. 150,000/Year',
    bedroom: 2,
    bathroom: 2,
    address: 'Ramapuram',
  },
  {
    id: 3,
    name: 'Chill House',
    image: require('../assets/images/house1.jpg'),
    housePackage: 'Rs. 500,000/Year',
    bedroom: 6,
    bathroom: 4,
    address: 'Tambaram',
  },
  {
    id: 4,
    name: 'Arch House',
    image: require('../assets/images/house4.jpg'),
    housePackage: 'Rs. 110,000/Year',
    bedroom: 3,
    bathroom: 2,
    address: 'Guindy',
  },
  {
    id: 5,
    name: 'Orchad House',
    image: require('../assets/images/house1.jpg'),
    housePackage: 'Rs. 400,000/Year',
    bedroom: 4,
    bathroom: 2,
    address: 'Koyambedu',
  },
];
